### PR TITLE
Update apache-netbeans.icns

### PR DESCRIPTION
**Pull request by mhalachev**
Update NetBeans app icon for macOS to match current design guidelines.

icon

The logo itself is precisely aligned to the recommended icon grid:

grid

Here's how it would appear in the dock, alongside other icons:

dock

### CODE REVIEW

**Comment by eirikbakke** [comment]
Thanks for this! Addressing an earlier comment from the other thread:

> Additionally, maintaining a white background color would ensure consistency with both the splash screen and the about dialog, as in both cases the logo is presented on a white background with no effects applied.

For the dock icon, I think the consistency should be with other dock icons, rather than with the NetBeans splash screen (which is very minimal just due to my own lack of artistic skills), so I'd argue in favor of keeping the background shading that was shown in an earlier version (https://user-images.githubusercontent.com/2364606/133636825-ef6804ee-d4a5-4941-9821-5ce9151c2bb7.png). Otherwise the icon looks very bright. The inside of the logo should still be its official white/grey colors, of course.

**Comment by eirikbakke** [comment]
Thanks, @mhalachev! The first one of those two looks good to go for me. Most branding manuals discourage "extending" logos in any way, so I think the simpler top one of the two is best to use. (But it quickly gets subjective, of course...)

**Comment by mhalachev** [comment]
All right, I'll prepare an icon set and update the PR when it's ready.

**Review by eirikbakke — APPROVED** [review]
Very nice; thank you! I looked at the icns files before/after in Preview on MacOS, and the changes seem sane (old/new resolutions seeming to be the same etc.).

@neilcsmith-net I'm not very familiar with how these icns files actually end up being installed or packaged. Does this change need to be made in any other repo as well, or is this one enough?

**Comment by neilcsmith-net** [comment]
Any changes should be in both netbeans and netbeans-nbpackage repos.  In fact, the main netbeans repo should really be the canonical location, and this should be kept in sync with it.  That's what I meant by matching PR here in https://github.com/apache/netbeans/pull/3168#issuecomment-1966409553 The icon here is used for the app bundle and installer, but the icon is also referenced in the IDE launcher script.

The icon looks good to me, but should go through review into the IDE repo before merging here.  I'm not sure about @matthiasblaesing comments about use of `netbeans.icns` away from macOS.  It could be we merge the svg icon from NBPackage into the IDE repo for that purpose instead??

**Comment by oyarzun** [comment]
+1 adding the standard svg icon to the IDE repo for use on a Linux desktop.

And maybe adding a PR that will update the frame icon for macOS when NetBeans is minimized (https://github.com/apache/netbeans/pull/3168#issuecomment-1171699186). 
@mhalachev  Do you have an svg version of the icns?

**Comment by mbien** [comment]
> +1 adding the standard svg icon to the IDE repo for use on a Linux desktop.

I am pretty sure this is only about mac. I don't see why the other icons should use the mac os guidelines. The borderless icon looked fine on the systems I tested it with (if i remember correctly).

e.g quick launch bar on manjaro/cinnamon: 
image

**Comment by neilcsmith-net** [comment]
@mbien see the comment at https://github.com/apache/netbeans/pull/3168#issuecomment-920260749 about Gnome Shell.  The SVG icon in this repo is used in the DEB and RPM, and quite well tested in Gnome Shell.  The question is more about if we make the icns file macOS specific, providing a usable SVG for use elsewhere.

**Comment by mbien** [comment]
@neilcsmith-net I agree with the linked comment. 
 - using mac guidelines on mac -> great. 
 - keeping the regular SVG for other systems -> also good, I don't think anyone complained about it so far. (since it has no border it is fairly portable and its difficult to make it look bad)
 - adding more SVGs to the repo for dark/light etc to let users pick a different one fitting to the theme -> why not

**Comment by neilcsmith-net** [comment]
@mbien so do I, hence the suggestion!  It would hopefully remove the objection to changing the icns file, or having to provide a bespoke mac version.  There isn't currently an svg icon in the main repo that works correctly, anyway - see comments on https://github.com/apache/netbeans-nbpackage/commit/a1acd0729baeb25422ba2a2c5f6828a2845a6fa6

**Comment by eirikbakke** [comment]
> using mac guidelines on mac -> great.
> keeping the regular SVG for other systems -> also good,

Agree with this; the new icon is only needed/desirable for MacOS, where it needs to look good next to other icons in the same style. If the "icns" file format is useful on Linux as well, then the previous version can be kept around as well.

(That does mean there is a "bespoke mac version", though, but I think that's fine.)

**Review by neilcsmith-net — CHANGES_REQUESTED** [review]
Just marking as request changes to ensure this doesn't get merged until this change is reflected in the main IDE repo.  This PR shouldn't be merged until after that, and any change from main repo review incorporated.

It might be worth considering a rethink to extract the icons from the NetBeans zip during NBPackage execution, but there needs to be a fallback in place so that would need addressing.

**Comment by mhalachev** [comment]
Thank you for your feedback!

> Just marking as request changes to ensure this doesn't get merged until this change is reflected in the main IDE repo. 

@neilcsmith-net I'll open a matching PR there.

> Agree with this; the new icon is only needed/desirable for MacOS, where it needs to look good next to other icons in the same style.

As @eirikbakke mentioned, this is indeed specific to macOS, the original icon is ok on other platforms as seen on the screenshots @mbien provided. 

> Do you have an svg version of the icns?

@oyarzun  No, the `.icns` was initially designed as a set of bitmaps in various resolutions. However, you can find the original icon as svg in this repo.

> And maybe adding a PR that will update the frame icon for macOS when NetBeans is minimized ([apache/netbeans#3168 (comment)](https://github.com/apache/netbeans/pull/3168#issuecomment-1171699186)). 

It would be nice to address this as well. Can we go even further and find a way to provide a thumbnail for the minimised window, as currently minimising the application results in having two NetBeans icons in the Dock?
 
minimised

**Comment by eirikbakke** [comment]
> Just marking as request changes to ensure this doesn't get merged until this change is reflected in the main IDE repo. This PR shouldn't be merged until after that, and any change from main repo review incorporated.

I assume https://github.com/apache/netbeans/pull/7132 is the corresponding change in the main IDE repo. The icns file there looks good, too.

**Comment by eirikbakke** [comment]
> Just marking as request changes to ensure this doesn't get merged until this change is reflected in the main IDE repo. This PR shouldn't be merged until after that, and any change from main repo review incorporated.

I assume https://github.com/apache/netbeans/pull/7127 is the corresponding change in the main IDE repo. I confirmed that the icns file there is identical.

**Comment by mhalachev** [comment]
Yes, it's the same icon.

**Comment by oyarzun** [comment]
@neilcsmith-net https://github.com/apache/netbeans/pull/7127 has been merged into the NetBeans repo, shall we merge this one as well?

**Comment by neilcsmith-net** [comment]
Yes, lets merge!  Thanks @mhalachev 

Strictly speaking not required for NB22 as can be worked around in config, but probably better we look to release a version of NBPackage before the final release binaries for NB22 are produced.  cc/ @ebarboni so he's aware on that.

**Comment by mhalachev** [comment]
Thanks!

**Comment by mbien** [comment]
I noticed while testing the NB22 release that my quicklaunch shortcut on linux was actually using the `.icns` file since there was no other vector graphics file it could use (I can't select the png), it looks now like:

image

so +1 for adding the svg to the next release too, since I have to switch to netbeans.svg provided by my OS theme to restore the old look:
image

There is also the risk that linux distributions will start using the mac icon at some point since most migrated away from `.png`s by now and there is no svg in `./nb`

**Comment by mhalachev** [comment]
@mbien Indeed, This behavior is not intended and should be addressed.

> It could be we merge the svg icon from NBPackage into the IDE repo for that purpose instead??

Could it be resolved like @neilcsmith-net suggested earlier in this thread?

PS: The icon in `netbeans-nbpackage`: [apache-netbeans.svg](https://github.com/apache/netbeans-nbpackage/blob/85d3584e76bcccba6f072dac285735c303bdf729/src/main/resources/org/apache/netbeans/nbpackage/apache-netbeans.svg)

**Comment by mbien** [comment]
filed https://github.com/apache/netbeans/issues/7734 since I just got reminded of it again while testing NB 23

**Pull request merged**
