### PR TITLE
Add Maven Wrapper (only-script) configured to use Maven 3.9.3.

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Add Maven Wrapper configured to use Maven 3.9.3.

- Ran `mvn wrapper:wrapper -Dmaven=3.9.3 -Dtype=only-script`
- Manually added SHA256
- Updated workflow to use wrapper

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
I'd forgotten the "linux" build workflow is now cross-platform, but seems Windows Powershell is working fine with that syntax anyway ..

**Comment by ebarboni** [comment]
LGTM

**Review by ebarboni — APPROVED** [review]

**Comment by mbien** [comment]
the maven wrapper script is actually pretty cool, it even uses a java single-class-program as fallback download option :)

**Comment by neilcsmith-net** [comment]
@mbien yes, saw that - hadn't looked at the new script option until last week when adding mvnw to another project.  Some interesting things in there, although with a few caveats for now.  The Windows one might also be interesting to look at - I wonder if a batch to powershell launcher option could work for the IDE?

**Comment by mbien** [comment]
> I wonder if a batch to powershell launcher option could work for the IDE?

worth a try. Esp since old systems like win 7 are essentially gone now. I remember that starting programs via scripts on old windows systems had problems like not being able to close the command prompt or having it pop up for a split second etc. I bet those issues are solved by now - not sure.

**Pull request merged**
